version: 41
imports:
- projectPath: common/java/gradle-fatjar
  revision: main
jobs:
- name: Push to Github
  steps:
  - type: PushRepository
    name: Github
    remoteUrl: https://github.com/Danish-Sensor-Engineering/dse-demo-serial-java
    userName: mnellemann
    passwordSecret: GITHUB-TOKEN
    force: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: main
    projects: dse/dse-demo-serial-java
  jobDependencies:
  - jobName: Test
    requireSuccessful: true
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
